# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('server_api_url', models.URLField(max_length=256, verbose_name='URL')),
                ('server_apikey', models.CharField(max_length=256, verbose_name='API key')),
                ('groupID', models.CharField(blank=True, max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
