# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etherpad', '0002_remove_pad_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='server_api_url',
        ),
        migrations.RemoveField(
            model_name='pad',
            name='server_apikey',
        ),
    ]
