# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etherpad', '0003_auto_20180606_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='groupID',
        ),
    ]
