# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpad', '0004_remove_pad_groupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=256, verbose_name='URL')),
                ('notes', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'server',
            },
        ),
    ]
