# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etherpad', '0005_padserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(blank=True, max_length=256)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etherpad.PadServer')),
            ],
            options={
                'verbose_name': 'group',
            },
        ),
        migrations.AddField(
            model_name='pad',
            name='server',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='etherpad.PadServer'),
        ),
        migrations.AddField(
            model_name='pad',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='etherpad.PadGroup'),
        ),
    ]
