# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpad', '0006_auto_20180607_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padserver',
            name='notes',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
